### ISSUE TITLE
Rename formula

### ISSUE THREAD

**Issue by EvaSDK** [corux/gitlab-omnibus-formula#4]
In order to avoid confusion with the existing formula https://github.com/saltstack-formulas/gitlab-formula, it would be nice to rename this one as gitlab-omnibus-formula. It would also make it clear it is intended to deal with omnibus packages only.

**Comment by corux** [comment]
Thanks for the suggestion. The formula and its states are now renamed.

**Comment by EvaSDK** [comment]
Thanks a lot.
